// Fill out your copyright notice in the Description page of Project Settings.


#include "GsUITrayLongPressBar.h"
#include "Components/ProgressBar.h"
#include "T1Project.h"
#include "UMG/Public/Blueprint/SlateBlueprintLibrary.h"


void UGsUITrayLongPressBar::NativeOnInitialized()
{
	Super::NativeOnInitialized();

	_progressBar->SetPercent(0.0f);
	_time = 0.f;
}

void UGsUITrayLongPressBar::NativeConstruct()
{
	Super::NativeConstruct();
	_time = 0.f;
	_isFullGauge = false;

	// CachedGeometryฐก ฐ่ป๊ตวพ๎ ม฿พำภธทฮ ภงฤกมถมคภฬ ณกณฏถงฑ๎ม๖ ฐจร็ตา	
	if (_bReserveShow)
	{
		SetRenderOpacity(0.0f);
	}
}

void UGsUITrayLongPressBar::NativeDestruct()
{
	if (_onFinishedLongPress.IsBound())
	{
		_onFinishedLongPress.Clear();
	}

	_progressBar->SetPercent(0.0f);
	_time = 0.f;

	_bReserveShow = false;

	Super::NativeDestruct();
}

void UGsUITrayLongPressBar::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
	Super::NativeTick(MyGeometry, InDeltaTime);

	if (_isFullGauge)
		return;

	if (_bReserveShow)
	{
		if (false == MyGeometry.GetLocalSize().IsZero())
		{
			_bReserveShow = false;

			FVector2D targetPos = _absTargetPos;
			targetPos.X -= MyGeometry.GetAbsoluteSize().X * 0.5f;

			FVector2D pixel;
			FVector2D viewport;
			USlateBlueprintLibrary::AbsoluteToViewport(this, targetPos, pixel, viewport);

			SetPositionInViewport(pixel);
			SetRenderOpacity(1.0f);
		}
	}

	if (1.0f <= _progressBar->Percent)
	{
		OnFinished();
		return;
	}

	// 1รสด็ ฑโมุภธทฮ ผณมค
	// 0รส ผณมคภฬธ้ นูทฮ ถ฿ฐิวิ
	if (0.f >= _longPressTotalDurationTime)
	{
		_progressBar->SetPercent(1.0f);
		OnFinished();
	}
	else
	{
		// 1รสธฆ ธฦฝรธุภธทฮ ตฮฐํ, 1รสธฆ ณัฐิ ภิทยวฯธ้ 1รสทฮ ฐฃมึวัดู
		_longPressTotalDurationTime = 1.f < _longPressTotalDurationTime ? 1.f : _longPressTotalDurationTime;
		_time += InDeltaTime;
		float percent = _time / _longPressTotalDurationTime;
		_progressBar->SetPercent(percent);
	}
	//GSLOG(Warning, TEXT("[UGsUITrayLongPressBar::NativeTick] - InDeltaTime: %f"), InDeltaTime);
}

void UGsUITrayLongPressBar::OnFinished()
{
	_isFullGauge = true;

	_onFinishedLongPress.Broadcast(_isFullGauge);

	CloseUI();
}

void UGsUITrayLongPressBar::CloseUI()
{
	Close();
}

void UGsUITrayLongPressBar::SetTargetPosition(const FVector2D& InAbsPos)
{
	_absTargetPos = InAbsPos;
	_bReserveShow = true;

	SetPositionInViewport(FVector2D::ZeroVector);
}
