// Fill out your copyright notice in the Description page of Project Settings.


#include "GsUIReuseItemIconSlotHud.h"
#include "T1Project.h"
#include "Item/GsItem.h"
#include "Item/GsItemManager.h"
#include "UI/UILib/Base/GsUIVFX.h"
#include "UI/UIControlLib/ContentWidget/GsButton.h"
#include "UI/UIControlLib/Control/GsDynamicIconSlotHelper.h"
#include "UI/UIContent/Common/Icon/GsUIIconItemInventory.h"
#include "UI/UIContent/Common/Icon/GsUIIconItem.h"
#include "Management/GsMessageHolder.h"
#include "Management/ScopeGlobal/GsSkillManager.h"
#include "Management/ScopeGame/GsQuickSlotManager.h"
#include "Message/MessageParam/GsItemContentsMessageParam.h"




void UGsUIReuseItemIconSlotHud::NativeOnInitialized()
{
	Super::NativeOnInitialized();

	_removeBtn->OnClicked.AddDynamic(this, &UGsUIReuseItemIconSlotHud::OnClickSlotRemove);

	_dragDownLogic.OnSlotDragDownTranslation.BindUObject(this, &UGsUIReuseItemIconSlotHud::OnSlotDragDownTranslation);
	_dragDownLogic.OnSlotDragDownStateChanged.BindUObject(this, &UGsUIReuseItemIconSlotHud::OnSlotDragDownStateChanged);
}

void UGsUIReuseItemIconSlotHud::NativeConstruct()
{
	Super::NativeConstruct();

	_autoEffectState = -1;
	_dragDownLogic.SetSensitiveValue(_dragDownSensitive);
	_dragDownLogic.SetDragDownValue(_dragDownValue);
}

FReply UGsUIReuseItemIconSlotHud::NativeOnTouchMoved(const FGeometry& InGeometry, const FPointerEvent& InGestureEvent)
{
	// №цЖ°¶§№®ҝЎ TouchStartҙВ ҫИөйҫоҝИ
	// БЦАЗ: №цЖ°АМ PreciseClick ҝЙјЗАП ¶§ёё АМ°чҝЎ өйҫоҝВҙЩ
	FReply reply = Super::NativeOnTouchMoved(InGeometry, InGestureEvent);

	if (_bIsCaptureMouse)
	{
		if (false == _pressStartPosAbs.IsZero())
		{
			if (_bCanDragDown)
			{
				_dragDownLogic.OnMouseButtonMove(InGeometry, InGestureEvent);
			}

			FVector2D startPos = InGeometry.AbsoluteToLocal(_pressStartPosAbs);
			FVector2D movePos = InGeometry.AbsoluteToLocal(InGestureEvent.GetScreenSpacePosition());			
			float diffY = FMath::Abs(startPos.Y - movePos.Y);
			float diffX = FMath::Abs(startPos.X - movePos.X);

			// ҪәЕ©·СА» №жЗШЗПҙВ №®БҰ·О XГаөө ГјЕ©
			if (_dragDownSensitive < diffY &&
				_dragDownSensitive > diffX)
			{
				return FReply::Handled().CaptureMouse(TakeWidget());
			}
		}
	}

	return Super::NativeOnTouchMoved(InGeometry, InGestureEvent);
}

FReply UGsUIReuseItemIconSlotHud::NativeOnTouchEnded(const FGeometry& InGeometry, const FPointerEvent& InGestureEvent)
{
	Super::NativeOnTouchEnded(InGeometry, InGestureEvent);

	_pressStartPosAbs = FVector2D::ZeroVector;

	if (_bIsCaptureMouse)
	{
		if (_bCanDragDown)
		{
			_dragDownLogic.OnButtonReleased();
		}

		_bIsCaptureMouse = false;

		return FReply::Handled().ReleaseMouseCapture();
	}

	_bIsCaptureMouse = false;

	return FReply::Unhandled();
}

void UGsUIReuseItemIconSlotHud::OnShow()
{
	Super::OnShow();

	
	SetBlinkEffect(false);			// ҪҪ·Ф ЕНДЎЗЯА»¶§
	SetEditModeEffect(false);		// ҪҪ·Ф ЖнБэ ёрөеАП¶§

	SetUseAutoEffect(false, false, false);
	_removeBtn->SetVisibility(ESlateVisibility::Collapsed);

	//SetUseAutoEffect(false);		// јТАҜБЯАО ҫЖАМЕЫАМ АЪөҝёрөе јіБӨ өЗҫоАЦА»¶§
	//SetNotOwnedAutoEffect(false);	// әсјТАҜБЯАО ҫЖАМЕЫАМ АЪөҝёрөе јіБӨ өЗҫоАЦА»¶§
}

void UGsUIReuseItemIconSlotHud::OnHide()
{

	Super::OnHide();
}

void UGsUIReuseItemIconSlotHud::OnClickSlotRemove()
{
	if (true == _isBlockState)
		return;

	FGsOnClickRemoveQuickSlotIcon paramData(_slotIndex);
	GMessage()->GetItemContents().SendMessage(MessageContentItem::QUICKSLOT_REMOVE, &paramData);

	_removeBtn->SetVisibility(ESlateVisibility::Collapsed);

	// close skill target select
	GSkill()->SetIsShowSkillTargetSelect(false);
}

void UGsUIReuseItemIconSlotHud::SetSlotItemIcon(const uint64 InItemDBID, const int32 InItemTID, const int64 InAmount, const uint8 InSlotIndex)
{
	_bCanDragDown = false;

	int32 prevAutoState = _autoEffectState;

	Super::SetSlotItemIcon(InItemDBID, InItemTID, InAmount, InSlotIndex);

	UGsQuickSlotManager* mgr = GSQuickSlot();
	const QuickSlotInfo* slotInfo = mgr->GetQuickSlotInfoBySlotID(_slotIndex);
	if (nullptr == slotInfo)
		return;

	//OnChangeSlotRemoveBtnVisible();
	_bCanDragDown = mgr->IsAllowedAutoUseItem(_slotIndex);
	SetAutoUseImage(_bCanDragDown);
	SetGrayScaleImage(((0 >= slotInfo->mItemDBId) && (0 < slotInfo->mTemplateId)));
	SetEditModeEffect(mgr->IsEditMode());

	// ҫЖАМЕЫАМ АЪөҝ »зҝлөЗ°н АЦА» ¶§, °№јц°Ў БЩҫоөйёз °ӯБҰ·О ҝАЕд јјЖГАМ өЗҙВ №®БҰ јцБӨ(C2URWQ-6258)
	// АМАь БӨәёҝН ҙЩёҰ ¶§ёё јјЖГЗФ
	int32 currAutoState = GetAutoEffectState(slotInfo->mAutoUse, 
		(0 < slotInfo->mItemDBId) ? true : false,
		(0 < slotInfo->mTemplateId) ? true : false);
	if (prevAutoState != currAutoState)
	{
		SetUseAutoEffect(slotInfo->mAutoUse,
			(0 < slotInfo->mItemDBId) ? true : false,
			(0 < slotInfo->mTemplateId) ? true : false);
	}
}

void UGsUIReuseItemIconSlotHud::OnClickIconSlot(class UGsUIIconItem& InIcon)
{
	if (true == _isBlockState)
		return;

	if (IsTutorialInteraction())
	{
		return;
	}

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(&InIcon);
	if (nullptr == itemIcon)
	{
		return;
	}
	UGsQuickSlotManager* slotMgr = GSQuickSlot();

	SetBlinkEffect(true);
	FGsItem* itemData = itemIcon->GetItemIconData();
	int32 slotID = itemIcon->GetSlotIntParamData();
	UGsQuickSlotManager::SlotRegisterItemStateType  type = slotMgr->GetSlotRegisterStateType(slotID);
	slotMgr->SetQuickSlotSelectionItem(slotID, type == UGsQuickSlotManager::SlotRegisterItemStateType::Empty);
	if (slotMgr->IsEditMode())
	{
		if (true == FGsItem::IsValidItem(itemData) && type == UGsQuickSlotManager::SlotRegisterItemStateType::OwnedItem)
		{
			/*
			//itemData->IsUseItem()
			itemIcon->SetSlotEquipImage((false == slotMgr->IsConsumableItem(slotID))
				&& (false == slotMgr->IsEquippedItem(slotID)) && (false == slotMgr->IsIngredientItem(slotID)));

			itemIcon->SetSlotUnEquipImage((false == slotMgr->IsConsumableItem(slotID))
				&& (true == slotMgr->IsEquippedItem(slotID)) && (false == slotMgr->IsIngredientItem(slotID)));

			itemIcon->SetSlotUseImage((true == slotMgr->IsConsumableItem(slotID))
				&& (false == slotMgr->IsIngredientItem(slotID)));
				*/
			
			//itemIcon->SetSlotEquipImage((itemData->IsEquipment()) && (false == itemData->IsEquipped()));
			//itemIcon->SetSlotUnEquipImage((itemData->IsEquipment()) && (itemData->IsEquipped()));
			//itemIcon->SetSlotUseImage(itemData->IsUseItem());
		}
		_removeBtn->SetVisibility(type != UGsQuickSlotManager::SlotRegisterItemStateType::Empty ? ESlateVisibility::Visible : ESlateVisibility::Collapsed);
		slotMgr->CheckSelectionInfo();
	}
	else
	{
		// өе·ЎұЧ·О ҝАЕдјіБӨА» ЗЯҙВөҘ ҝөҝӘ ҫИАМ¶у Е¬ёҜ ЖЗБӨАМ іҜ °жҝм Е¬ёҜ №«ҪГ
		if (_bAutoChanged)
		{
			slotMgr->ResetQuickSlotSelectionInfo();
			return;
		}

		// Edit »уЕВ°Ў ҫЖҙТ¶§ҙВ №Щ·О »зҝл Гіё®
		if (true == FGsItem::IsValidItem(itemData) && type == UGsQuickSlotManager::SlotRegisterItemStateType::OwnedItem)
		{
			FGsOnClickUseQuickSlotItem paramData(slotID);
			GMessage()->GetItemContents().SendMessage(MessageContentItem::QUICKSLOT_USE, &paramData);	
		}
		slotMgr->ResetQuickSlotSelectionInfo();
	}
	// close skill target select
	GSkill()->SetIsShowSkillTargetSelect(false);
}

void UGsUIReuseItemIconSlotHud::ResetSelection()
{
	SetEquipTextImage(false);
	SetUnEquipTextImage(false);
	SetUseTextImage(false);

	_removeBtn->SetVisibility(ESlateVisibility::Collapsed);
}

void UGsUIReuseItemIconSlotHud::SetSlotDimmed(const bool InState)
{
	_isBlockState = InState;

	if (nullptr == _iconSlotHelper->GetIcon(0))
		return;

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(_iconSlotHelper->GetIcon(0));
	if (nullptr == itemIcon)
		return;

	itemIcon->SetDimmedImage(InState);
}

void UGsUIReuseItemIconSlotHud::SetGrayScaleImage(const bool InState)
{
	if (nullptr == _iconSlotHelper->GetIcon(0))
		return;

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(_iconSlotHelper->GetIcon(0));
	if (nullptr == itemIcon)
		return;

	itemIcon->SetImageGrayscale(InState);
}

void UGsUIReuseItemIconSlotHud::SetAutoUseImage(const bool InState)
{
	if (nullptr == _iconSlotHelper->GetIcon(0))
		return;

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(_iconSlotHelper->GetIcon(0));
	if (nullptr == itemIcon)
		return;

	itemIcon->SetAutoImage(InState);
}

void UGsUIReuseItemIconSlotHud::SetEquipTextImage(const bool InState)
{
	if (nullptr == _iconSlotHelper->GetIcon(0))
		return;

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(_iconSlotHelper->GetIcon(0));
	if (nullptr == itemIcon)
		return;

	itemIcon->SetSlotEquipImage(InState);
}

void UGsUIReuseItemIconSlotHud::SetUnEquipTextImage(const bool InState)
{
	if (nullptr == _iconSlotHelper->GetIcon(0))
		return;

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(_iconSlotHelper->GetIcon(0));
	if (nullptr == itemIcon)
		return;

	itemIcon->SetSlotUnEquipImage(InState);
}

void UGsUIReuseItemIconSlotHud::SetUseTextImage(const bool InState)
{
	if (nullptr == _iconSlotHelper->GetIcon(0))
		return;

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(_iconSlotHelper->GetIcon(0));
	if (nullptr == itemIcon)
		return;

	itemIcon->SetSlotUseImage(InState);
}

void UGsUIReuseItemIconSlotHud::SetBlinkEffect(bool InState)
{
	if (true == InState)
	{
		if (_quickSlotBlinkEffect->IsPlayingAnimation())
		{
			_quickSlotBlinkEffect->HideVFX();
		}
		_quickSlotBlinkEffect->ShowVFX();
	}
	else
	{
		_quickSlotBlinkEffect->HideVFX();
	}
}

void UGsUIReuseItemIconSlotHud::SetEditModeEffect(bool InState)
{
	if (true == InState)
	{
		if (_quickSlotEditEffect->IsPlayingAnimation())
		{
			return;
		}
		_quickSlotEditEffect->ShowVFX();
	}
	else
	{
		_quickSlotEditEffect->HideVFX();
	}
}

void UGsUIReuseItemIconSlotHud::SetUseAutoEffect(bool InAutoUse, bool IsItemDBId, bool IsTemplateId)
{
	_autoEffectState = GetAutoEffectState(InAutoUse, IsItemDBId, IsTemplateId);

	_dragDownLogic.SetIsDown(InAutoUse, false);

	switch (_autoEffectState)
	{
	case 1:
		_quickSlotUseAutoEffect->ShowVFX();
		_notOwnedUseAutoEffect->HideVFX();
		break;
	case 2:
		_quickSlotUseAutoEffect->HideVFX();
		_notOwnedUseAutoEffect->ShowVFX();
		break;
	default:
		_quickSlotUseAutoEffect->HideVFX();
		_notOwnedUseAutoEffect->HideVFX();
		break;
	}
}

int32 UGsUIReuseItemIconSlotHud::GetAutoEffectState(bool InAutoUse, bool IsItemDBId, bool IsTemplateId)
{
	if (InAutoUse)
	{
		if (IsItemDBId)
		{
			// јТАҜБЯАО ҫЖАМЕЫАМ АЪөҝёрөе јіБӨ өЗҫоАЦА»¶§
			return 1;
		}
		else
		{
			if (IsTemplateId)
			{
				// әсјТАҜБЯАО ҫЖАМЕЫАМ АЪөҝёрөе јіБӨ өЗҫоАЦА»¶§
				return 2;
			}
		}
	}

	return 0;
}

void UGsUIReuseItemIconSlotHud::InvalidateAutoState()
{
	if (UGsQuickSlotManager* quickSlotMgr = GSQuickSlot())
	{
		if (const QuickSlotInfo* slotInfo = quickSlotMgr->GetQuickSlotInfoBySlotID(_slotIndex))
		{
			SetUseAutoEffect(slotInfo->mAutoUse,
				(0 < slotInfo->mItemDBId) ? true : false,
				(0 < slotInfo->mTemplateId) ? true : false);
		}
	}
}

void UGsUIReuseItemIconSlotHud::OnRefreshIconWrapBox(int32 InIndex, UGsUIIconBase* InIcon)
{
	Super::OnRefreshIconWrapBox(InIndex, InIcon);

	// әу ҪҪ·Ф ЖЗБӨіӯ °жҝм
	if (0 >= _itemDBID && 0 >= _itemTID)
	{
		SetUseAutoEffect(false, false, false);
	}

	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(InIcon);
	if (nullptr == itemIcon)
	{
		return;
	}	

	if (false == itemIcon->OnButtonDownSlot.IsBoundToObject(this))
	{
		itemIcon->OnButtonDownSlot.Unbind();
		itemIcon->OnButtonDownSlot.BindUObject(this, &UGsUIReuseItemIconSlotHud::OnItemSlotButtonDown);
	}

	if (false == itemIcon->OnButtonReleaseSlot.IsBoundToObject(this))
	{
		itemIcon->OnButtonReleaseSlot.Unbind();
		itemIcon->OnButtonReleaseSlot.BindUObject(this, &UGsUIReuseItemIconSlotHud::OnItemSlotButtonRelease);
	}
}

void UGsUIReuseItemIconSlotHud::OnClickIconWindowInput()
{
	if (nullptr != _iconSlotHelper)
	{
		UGsUIIconBase* iconBase = _iconSlotHelper->GetIcon(0);
		if (nullptr == iconBase)
			return;

		UGsUIIconItem* iconItem = Cast<UGsUIIconItem>(iconBase);
		if (nullptr == iconItem)
			return;

		OnClickIconSlot(*iconItem);
	}
}

void UGsUIReuseItemIconSlotHud::OnItemSlotButtonDown(const FGeometry& Geometry, const FPointerEvent& MouseEvent)
{
	_bAutoChanged = false;

	// БЦАЗ: №цЖ°АМ АЦАёёй NativeOnTouchStarted °Ў ҫИөйҫоҝА№З·О ҝ©ұвјӯ АъАе. 
	// °и»кА» №цЖ°АМ ҫЖҙС А§Б¬Аё·О ЗТ°Е¶у ·ОДГБВЗҘ·О әҜИҜЗПБц ҫКАә АэҙлБВЗҘ АъАе
	if (false == _bIsCaptureMouse)
	{
		_bIsCaptureMouse = true;
		_pressStartPosAbs = MouseEvent.GetScreenSpacePosition();

		if (_bCanDragDown)
		{
			_dragDownLogic.OnMouseButtonDown(Geometry, MouseEvent);
		}
	}
}

void UGsUIReuseItemIconSlotHud::OnItemSlotButtonRelease()
{
	// ҪәЕ©·С ЖЗБӨ ИӨАә ДёГДөЗБц ҫКАә »уЕВҝЎјӯ ҝөҝӘ №ЫАё·О іӘ°Ј°жҝмҝЎ ГКұвИӯ А§ЗФ
	if (_bIsCaptureMouse)
	{
		if (false == HasMouseCapture())
		{
			_bIsCaptureMouse = false;
			_pressStartPosAbs = FVector2D::ZeroVector;
		}
	}
}

void UGsUIReuseItemIconSlotHud::OnSlotDragDownTranslation(const FVector2D& InTranslation)
{	
	SetRenderTranslation(InTranslation);
}

void UGsUIReuseItemIconSlotHud::OnSlotDragDownStateChanged()
{
	// ҝАЕд јјЖГ АМәҘЖ® әёі»ұв °ь·Г Гіё®
	if (_bCanDragDown)
	{
		_bAutoChanged = true;

		if (UGsUIIconBase* icon = _iconSlotHelper->GetIcon(0))
		{
			if (UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(icon))
			{
				int32 slotId = itemIcon->GetSlotIntParamData();
				GSQuickSlot()->SetAutoState(slotId);
			}
		}

		if (IsTutorialInteraction())
		{
			OnTutorialInteraction.ExecuteIfBound();
		}
	}
}
