// Fill out your copyright notice in the Description page of Project Settings.


#include "GsUITrayEnchantItemWait.h"
#include "UI/UIControlLib/ContentWidget/GsButton.h"
#include "Management/ScopeGame/GsItemEnchantManager.h"
#include "../Management/GsScopeGame.h"
#include "../Management/GsScopeHolder.h"


void UGsUITrayEnchantItemWait::NativeConstruct()
{
	Super::NativeConstruct();
	
	_btnConfirm->OnClicked.AddDynamic(this, &UGsUITrayEnchantItemWait::OnClickConfirm);
	
	FGsItemEnchantManager* mgr = GSItemEnchant();
	if (mgr)
	{
		mgr->PlayEffectSound(FGsItemEnchantManager::EnchantEffectSoundResType::SingleEnchant_NotSafe_Wait);
	}
}

void UGsUITrayEnchantItemWait::NativeDestruct()
{
	_btnConfirm->OnClicked.RemoveDynamic(this, &UGsUITrayEnchantItemWait::OnClickConfirm);

	_confirmCallback = nullptr;
	_currentTime = 0.f;
	_lockMaxTime = 0.f;

	FGsItemEnchantManager* mgr = GSItemEnchant();
	if (mgr)
	{
		mgr->StopEffectSound(FGsItemEnchantManager::EnchantEffectSoundResType::SingleEnchant_NotSafe_Wait);
	}

	Super::NativeDestruct();
}

void UGsUITrayEnchantItemWait::OnClickConfirm()
{
	FGsItemEnchantManager* mgr = GSItemEnchant();
	if (mgr)
	{
		if (false == mgr->IsOpenItemEnchangWidget())
		{
			Close();
		}
	}

	if (false == IsPossibleOnClick())
		return;

	if (nullptr != _confirmCallback)
	{
		// ม฿บน ภ็ลฌธฏภฬ พศตวตตทฯ ภำฝรทฮ ธทภฝ
		_currentTime = 0.f;
		_lockMaxTime = 10.0f;

		_confirmCallback();
	}
	else
	{
		Close();
	}
}

bool UGsUITrayEnchantItemWait::IsPossibleOnClick() const
{
	return (_currentTime >= _lockMaxTime);
}

void UGsUITrayEnchantItemWait::SetData(float InBtnLockTime, TFunction<void()> InConfirmCallback)
{
	_lockMaxTime = InBtnLockTime;
	_confirmCallback = InConfirmCallback;
}

// น๖ฦฐ ลฌธฏฑ๎ม๖ 1รส มคตตภว ลาภป ตา (นูทฮ ฑคลฌทฮ ภฮวั ศคภฬณช ฒฟภำว๖ป๓ นๆม๖ / ธฎดฯม๖2m ตฟภฯวิ)
void UGsUITrayEnchantItemWait::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
	_currentTime += InDeltaTime;
}