// Fill out your copyright notice in the Description page of Project Settings.


#include "UI/UIContent/Tray/ItemEnchant/GsUITrayEnchantResultPreserved.h"
#include "Components/TextBlock.h"
#include "Components/PanelWidget.h"
#include "Item/GsItem.h"
#include "Item/GsItemEquipment.h"
#include "Item/GsItemManager.h"
#include "UI/UIControlLib/ContentWidget/GsButton.h"
#include "UI/UIControlLib/Control/GsDynamicIconSlotHelper.h"
#include "UI/UIControlLib/ContentWidget/GsHorizontalBoxIconSelector.h"
#include "UI/UIContent/Common/Icon/GsUIIconItemInventory.h"



void UGsUITrayEnchantResultPreserved::BeginDestroy()
{
	if (nullptr != _targetIconSlotHelper)
	{
		_targetIconSlotHelper = nullptr;
	}

	Super::BeginDestroy();
}

void UGsUITrayEnchantResultPreserved::NativeOnInitialized()
{
	Super::NativeOnInitialized();

	if (nullptr == _targetIconSlotHelper)
	{
		_targetIconSlotHelper = NewObject<UGsDynamicIconSlotHelper>(this);
		_targetIconSlotHelper->Initialize(_targetItemIconSelector);
		_targetIconSlotHelper->OnRefreshIcon.AddDynamic(this, &UGsUITrayEnchantResultPreserved::OnRefreshTargetIcon);
		_targetIconSlotHelper->OnCreateIcon.AddDynamic(this, &UGsUITrayEnchantResultPreserved::OnCreateTargetIcon);
	}
}

void UGsUITrayEnchantResultPreserved::NativeConstruct()
{
	Super::NativeConstruct();

	// ЙіЦА ХЌИЏБюСі 2УЪ СЄЕЕРЧ ХвРЛ Ев (ЙйЗЮ БЄХЌЗЮ РЮЧб ШЄРЬГЊ ВПРгЧіЛѓ ЙцСі / ИЎДЯСі2m ЕПРЯЧд)
	_currentTime = 0.f;
	_lockMaxTime = 1.f;

	_btnConfirm->OnClicked.AddDynamic(this, &UGsUITrayEnchantResultPreserved::OnclickConfirm);
}

void UGsUITrayEnchantResultPreserved::NativeDestruct()
{
	_targetItemIconSelector->RemoveAllChildren();

	_targetItemDbid = 0;

	_btnConfirm->OnClicked.RemoveDynamic(this, &UGsUITrayEnchantResultPreserved::OnclickConfirm);

	Super::NativeDestruct();
}

void UGsUITrayEnchantResultPreserved::SetDisplayItem(const ItemDBId InItemDbid, float InLockMaxTime, bool InIsEnchant)
{
	_targetItemDbid = InItemDbid;
	_lockMaxTime = InLockMaxTime;
	
	if (InIsEnchant)
	{
		SetDisplayEnchant();
	}
	else
	{
		SetDisplayMagicalForge();
	}
}

void UGsUITrayEnchantResultPreserved::OnclickConfirm()
{
	if (false == IsPossibleOnClick())
		return;

	Close();
}

void UGsUITrayEnchantResultPreserved::OnRefreshTargetIcon(int32 InIndex, UGsUIIconBase* InIcon)
{
	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(InIcon);
	if (nullptr == itemIcon)
	{
		return;
	}

	itemIcon->SetOwnedItem(_targetItemDbid);
	itemIcon->SetItemNameVisibility(false);
	itemIcon->SetItemEnchantLevel(0);
}

void UGsUITrayEnchantResultPreserved::OnCreateTargetIcon(UGsUIIconBase* InIcon)
{
	UGsUIIconItemInventory* itemIcon = Cast<UGsUIIconItemInventory>(InIcon);
	if (nullptr == itemIcon)
	{
		return;
	}

	itemIcon->SetItemNameVisibility(false);
	//itemIcon->SetItemCount(0);
}

bool UGsUITrayEnchantResultPreserved::IsPossibleOnClick() const
{
	return (_currentTime >= _lockMaxTime);
}

void UGsUITrayEnchantResultPreserved::SetDisplayEnchant()
{
	UGsItemManager* itemManager = GItem();
	if (nullptr == itemManager)
		return;

	TWeakPtr<FGsItem> findItem = itemManager->FindItem(_targetItemDbid, ItemType::EQUIP);
	if (false == findItem.IsValid())
		return;

	// НЧЦа ЙЎБИ : А­Ш­ НЧЦа
	FText failText;
	FText::FindText(TEXT("ItemUIText"), TEXT("ItemUi_Enchant_Notice_Fail"), failText);
	_textBlockFail->SetText(failText);

	// ОЦРЬХл РЬИЇ
	FText itemNameText;
	GetItemNameText(findItem.Pin()->GetName(), findItem.Pin()->GetLevel(), itemNameText);
	_itemNameText->SetText(itemNameText);

	// ОЦРЬХл ОЦРЬФм
	_targetIconSlotHelper->RefreshAll(1);

	// УпАЁ СЄКИ АЈУпБт
	_panelCount->SetVisibility(ESlateVisibility::Collapsed);
}

void UGsUITrayEnchantResultPreserved::SetDisplayMagicalForge()
{
	UGsItemManager* itemManager = GItem();
	if (nullptr == itemManager)
		return;

	TWeakPtr<FGsItem> findItem = itemManager->FindItem(_targetItemDbid, ItemType::EQUIP);
	if (false == findItem.IsValid())
		return;

	FGsItemEquipment* equipmentItem = findItem.Pin()->GetCastItem<FGsItemEquipment>();
	if (nullptr == equipmentItem)
		return;

	// НЧЦа ЙЎБИ : ИЖЙ§РЧ ШћРЬ Ш№ОюСГНРДЯДй...
	FText failText;
	FText::FindText(TEXT("ItemUIText"), TEXT("ItemUi_MagicalForge_ResultFail"), failText);
	_textBlockFail->SetText(failText);

	// ОЦРЬХл РЬИЇ
	FText itemNameText;
	GetItemNameText(findItem.Pin()->GetName(), findItem.Pin()->GetLevel(), itemNameText);
	_itemNameText->SetText(itemNameText);

	// ОЦРЬХл ОЦРЬФм
	_targetIconSlotHelper->RefreshAll(1);

	// УпАЁ СЄКИ АЈУпБт
	_panelCount->SetVisibility(ESlateVisibility::SelfHitTestInvisible);
	_textBlockCount->SetText(FText::AsNumber(equipmentItem->GetMagicalForgeData().mLevel));
}

void UGsUITrayEnchantResultPreserved::GetItemNameText(const FText& InNameText, const Level InLevel, OUT FText& OutNameText)
{
	if (0 < InLevel)
	{
		FText mark;
		FText::FindText(TEXT("MarkFormatingText"), TEXT("Plus"), mark);
		FString resultStr = FString::Format(TEXT("{0}{1} {2}"), { *mark.ToString(), InLevel, *InNameText.ToString() });
		OutNameText = FText::FromString(resultStr);
	}
	else
	{
		OutNameText = InNameText;
	}
}

// ЙіЦА ХЌИЏБюСі 2УЪ СЄЕЕРЧ ХвРЛ Ев (ЙйЗЮ БЄХЌЗЮ РЮЧб ШЄРЬГЊ ВПРгЧіЛѓ ЙцСі / ИЎДЯСі2m ЕПРЯЧд)
void UGsUITrayEnchantResultPreserved::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
	_currentTime += InDeltaTime;
	Super::NativeTick(MyGeometry, InDeltaTime);
}