// Fill out your copyright notice in the Description page of Project Settings.


#include "GsUIWindowNetAddress.h"

#include "GsSchemaNetAddress.h"

#include "Management/ScopeGlobal/GsGameFlowManager.h"
#include "Management/ScopeLobby/GsLobbyDataManager.h"
#include "Management/ScopeGlobal/GsDivergenceManager.h"

#include "Components/WrapBox.h"
#include "Components/UniformGridPanel.h"
#include "Components/UniformGridSlot.h"
#include "UI/UIContent/Window/ServerSelect/GsUIServerListSlot.h"
#include "UI/UIControlLib/Control/GsDynamicPanelSlotHelper.h"
#include "UI/UIControlLib/ContentWidget/GsButton.h"
#include "UI/UIContent/Helper/GsUIHelper.h"


void UGsUIWindowNetAddress::NativeOnInitialized()
{
	// јӯ№ц ҪҪ·Ф өҝАы»эјә °ьё®°ҙГј »эјә
	_panelSlotHelper = NewObject<UGsDynamicPanelSlotHelper>(this);
	_panelSlotHelper->Initialize(_entryWidgetClass, _panelServerlist);
	_panelSlotHelper->OnRefreshEntry.AddDynamic(this, &UGsUIWindowNetAddress::OnRefreshEntry);

	if (nullptr != _btnConnect)
	{
		_btnConnect->OnClicked.AddDynamic(this, &UGsUIWindowNetAddress::OnClickConnect);
	}

	Super::NativeOnInitialized();
}

void UGsUIWindowNetAddress::BeginDestroy()
{
	if (_panelSlotHelper)
	{
		_panelSlotHelper->OnRefreshEntry.RemoveDynamic(this, &UGsUIWindowNetAddress::OnRefreshEntry);
	}
	_panelSlotHelper = nullptr;

	Super::BeginDestroy();
}


void UGsUIWindowNetAddress::NativeConstruct()
{
	_serverIndex = 0;

	Super::NativeConstruct();
}

void UGsUIWindowNetAddress::NativeDestruct()
{	
	Super::NativeConstruct();
}

void UGsUIWindowNetAddress::SetData(/*const FText& InWorldName*/)
{
	_listServer.Empty();

#ifdef LOBBY_FLOW_UI_HIVE_1ST
	if (UGsLobbyDataManager* lobbyDataMgr = LSLobbyData())
	{
		//_listServer = lobbyDataMgr->GetSeverList();

		if (const UGsTable* table = FGsSchemaNetAddress::GetStaticTable())
		{
			TArray<const FGsSchemaNetAddress*> allRow;

			if (false == table->GetAllRows(allRow))
			{
				return;
			}

			for (const FGsSchemaNetAddress* data : allRow)
			{
				FString rowName = data->GetRowName().ToString();
				_listServer.Emplace(rowName);
			}
		}

		int8 listNum = _listServer.Num();
		if (0 >= listNum)
			return;	

		_panelSlotHelper->RefreshAll(listNum);

		_toggleGroup.Clear();
		_toggleGroup.AddToggleWidgetByParentPanel(_panelServerlist);
		_toggleGroup.SetSelectedIndex(0);
	}
#else
#if WITH_EDITOR
	if (const UGsTable* table = FGsSchemaNetAddress::GetStaticTable())
	{
		TArray<const FGsSchemaNetAddress*> allRow;

		if (false == table->GetAllRows(allRow))
		{
			return;
		}

		for (const FGsSchemaNetAddress* data : allRow)
		{
			FString rowName = data->GetRowName().ToString();
			_listServer.Emplace(rowName);
		}
	}
#else
	_listServer = GDivergence()->GetAuthAgentNameList();		
#endif

	int8 listNum = _listServer.Num();
	if (0 >= listNum)
		return;

	_panelSlotHelper->RefreshAll(listNum);

	_toggleGroup.Clear();
	_toggleGroup.AddToggleWidgetByParentPanel(_panelServerlist);
	_toggleGroup.SetSelectedIndex(0);
#endif
}

void UGsUIWindowNetAddress::OnRefreshEntry(int32 InIndex, class UWidget* InEntry)
{
	// TODO: °ў ҪҪ·Фә° БӨәё Гіё®
	int serverNum = _listServer.Num();
	if (0 < serverNum &&
		InIndex <= serverNum)
	{
		// TODO: °ў ҪҪ·Фә° БӨәё Гіё®
		UGsUIServerListSlot* entry = Cast<UGsUIServerListSlot>(InEntry);
		if (entry)
		{
			const FString& serverName = _listServer[InIndex];
			(0 == InIndex) ? entry->SetData(InIndex, serverName, true) : entry->SetData(InIndex, serverName);
			entry->OnClickSlot.BindUObject(this, &UGsUIWindowNetAddress::OnClickSlot);
		}
	}
}

void UGsUIWindowNetAddress::OnClickSlot(int32 InIndex)
{
	// TODO: №ЩІп АОөҰҪәҝЎ ҙлЗС Гіё®
	GSLOG(Log, TEXT("[ServerSelect] list Index: %d"), InIndex);

	_serverIndex = InIndex;
	_toggleGroup.SetSelectedIndex(InIndex);
}

void UGsUIWindowNetAddress::OnClickConnect()
{
	int NumServerCnt = _listServer.Num();
	// bak1210 : _serverIndexҙВ АҪјц°ӘАМ ҫшҫо ГКұвИӯ өЙӢҡ 0Аё·О өЙ јц АЦ°н, №иҝӯЕ©ұвҝӘҪГ 0АПјц АЦҫо 0АП¶§ БўұЩЗТјц АЦҙВ ҝА·щ јцБӨ
	if ((NumServerCnt != 0) && (NumServerCnt >= _serverIndex))
	{
		OnClickServer.ExecuteIfBound(_serverIndex);
	}
}

bool UGsUIWindowNetAddress::OnBack()
{	
	FGsUIHelper::PopupQuitGame();

	// °ФАУ іӘ°Ўұв ЖЛҫчГўАМ ҫЖҙС Бҫ·бГўА» ¶зҝп °НАМ№З·О Super::OnBackёҰ ЕёБц ҫКАҪ
	return true;	
}
