// Fill out your copyright notice in the Description page of Project Settings.


#include "GsGameViewPortClient.h"
#include "SignificanceManager.h"
#include "Management/ScopeGame/GsGameObjectManager.h"
#include "GameObject/ObjectClass/GsGameObjectBase.h"
#include "Blueprint/WidgetLayoutLibrary.h"
#include "Framework/Application/SlateApplication.h"
#include "Data/GsDataContainManager.h"
#include "Data/GsGlobalConstant.h"
#include "Message/MessageParam/GsSystemMessageParam.h"
#include "Message/GsMessageSystem.h"
#include "Management/GsMessageHolder.h"
#include "Management/ScopeGlobal/GsUIManager.h"


void UGsGameViewPortClient::Init(struct FWorldContext& WorldContext, UGameInstance* OwningGameInstance, bool bCreateNewAudioDevice)
{
	Super::Init(WorldContext, OwningGameInstance, bCreateNewAudioDevice);

	_handleResize = FViewport::ViewportResizedEvent.AddUObject(this, &UGsGameViewPortClient::OnResizeViewport);
}

void UGsGameViewPortClient::BeginDestroy()
{
	if (_handleResize.IsValid())
	{
		FViewport::ViewportResizedEvent.Remove(_handleResize);
	}

	Super::BeginDestroy();
}

void UGsGameViewPortClient::Tick(float InDeltaTime)
{
	Super::Tick(InDeltaTime);

	if (_significantManager)
	{
		if ((nullptr != GetWorld()) && (nullptr != GSGameObject()))
		{

			if (UGsGameObjectBase * player = GSGameObject()->FindObject(EGsGameObjectType::LocalPlayer))
			{
				if (AActor * character = player->GetActor())
				{
					_viewPortArray.Empty();
					_viewPortArray.Add(character->GetTransform());
				}
			}
			_significantManager->Update(TArrayView<FTransform>(_viewPortArray));
		}
	}
}

void UGsGameViewPortClient::InitSignificanceManager()
{
	if (GetWorld())
	{
		_significantManager = USignificanceManager::Get(GetWorld());
	}	
}

void UGsGameViewPortClient::OnResizeViewport(FViewport* InViewport, uint32 InNum)
{
	UpdateDragTriggerDistance();
}

void UGsGameViewPortClient::UpdateDragTriggerDistance()
{
	if (nullptr == Viewport)
	{
		// РЬ АЊРЬ ОјРИИщ UWidgetLayoutLibrary::GetViewportScale ПЁМ­ ИХПь РлРК АЊРЬ ГбОюПШ
		return;
	}

	// ПЃСј БтКЛАЊРК 5. ИЎНКЦЎ ГЛ ЙіЦА ХЌИЏРЬ РпЕЧАд ИИЕщБт РЇЧи ЙЮАЈЕЕИІ ГЗУу
	float dragTriggerDistBase = 20.f;
	if (UGsUIManager* uiMgr = GUI())
	{
		if (uiMgr->IsHUDScale() ||
			uiMgr->IsLongDragTriggerDist())
		{
			// НКХГ ЙіЦА ХЌИЏРЬ РпЕЧАд ИИЕщБт РЇЧи ЙЮАЈЕЕИІ Дѕ ГЗУу
			dragTriggerDistBase = 50.f;
		}
	}

	// БтБтПЁ ЕћЖѓ ЕПРЯСЖАЧРЛ СжБт РЇЧи ScaleРЛ АіЧд
	float viewportScale = UWidgetLayoutLibrary::GetViewportScale(this);
	// ГЪЙЋ РЬЛѓЧб АЊРЛ ГжСі ОЪЕЕЗЯ ОЪЕЕЗЯ РкИЇ
	float dragTriggerDist = FMath::Clamp(dragTriggerDistBase * viewportScale, 5.f, 500.f);

	FSlateApplication::Get().SetDragTriggerDistance(dragTriggerDist);
}

void UGsGameViewPortClient::LostFocus(FViewport* InViewport)
{
	Super::LostFocus(InViewport);	

	if (nullptr == GScope())
	{
		return;
	}

	if (FGsMessageHolder* message = GMessage())
	{
		FGsViewPortFocusParam param(false);
		message->GetSystemParam().SendMessage(MessageSystem::VIEWPORT_LOST_FOCUS, &param);
		GSLOG(Log, TEXT("%s"), TEXT("=== LostFocus"));
	}
}

void UGsGameViewPortClient::ReceivedFocus(FViewport* InViewport)
{
	Super::ReceivedFocus(InViewport);

	if (nullptr == GScope())
	{
		return;
	}

	if (FGsMessageHolder* message = GMessage())
	{
		FGsViewPortFocusParam param(true);
		message->GetSystemParam().SendMessage(MessageSystem::VIEWPORT_RECEIVE_FOCUS, &param);
		GSLOG(Log, TEXT("%s"), TEXT("==== ReceivedFocus"));
	}
}