// Fill out your copyright notice in the Description page of Project Settings.


#include "GsUIBillboardTalkBalloon.h"

#include "CanvasPanel.h"
#include "Components/TextBlock.h"
#include "DrawDebugHelpers.h"
#include "Engine/World.h"
#include "FontMeasure.h"
#include "Framework/Application/SlateApplication.h"
#include "GameFramework/Actor.h"

#include "Achievement/GsAchievementData.h"

#include "DataSchema/TalkBalloon/GsSchemaTalkBalloonData.h"
#include "DataSchema/GameObject/Npc/GsSchemaNpcData.h"

#include "GameObject/Define/GsGameObjectDefine.h"

#include "GameObject/ObjectClass/GsGameObjectBase.h"
#include "GameObject/ObjectClass/GsGameObjectNonPlayerBase.h"

#include "Item/GsItemManager.h"

#include "Management/ScopeGame/GsGameObjectManager.h"
#include "Management/ScopeGame/GsAchievementManager.h"
#include "Management/ScopeGame/GsCommunityEventManager.h"
#include "Management/ScopeGlobal/GsOptionManager.h"
#include "Management/ScopeGlobal/GsGameDataManager.h"

#include "Management/GsMessageHolder.h"
#include "Message/MessageParam/GsGameObjectMessageParam.h"

#include "Net/GsNetSendService.h"

#include "Option/GsGameUserSettings.h"

#include "Rendering/SlateRenderer.h"

#include "UTIL/GsText.h"
#include "UTIL/GsTableUtil.h"
#include "UTIL/GsTimeSyncUtil.h"



void UGsUIBillboardTalkBalloon::NativeOnInitialized()
{
	_updateDelegateMap.Emplace(TalkBalloonState::Opened, FOnUpdateTalkBalloonDelegate::CreateUObject(
		this, &UGsUIBillboardTalkBalloon::UpdateOpened));
	_updateDelegateMap.Emplace(TalkBalloonState::Closing, FOnUpdateTalkBalloonDelegate::CreateUObject(
		this, &UGsUIBillboardTalkBalloon::UpdateClosing));
	_updateDelegateMap.Emplace(TalkBalloonState::Closed, FOnUpdateTalkBalloonDelegate::CreateUObject(
		this, &UGsUIBillboardTalkBalloon::UpdateClosed));
}

void UGsUIBillboardTalkBalloon::NativeConstruct()
{
	Super::NativeConstruct();

	EndTalkBalloon();
}

void UGsUIBillboardTalkBalloon::NativeDestruct()
{
	_localPlayer = nullptr;

	Super::NativeDestruct();
}

void UGsUIBillboardTalkBalloon::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
	Super::NativeTick(MyGeometry, InDeltaTime);

	if (nullptr == _talkBalloonData)
		return;

	if (GGameData()->GetInvasionDefenseState())
	{
		// Ä§°řŔü ÁřÇŕ Áß
		if (false == IsClosed())
		{
			SetClose();
		}
	}
	else
	{
		if (IsOptionEnabled())
		{
			_isOptionEnd = false;
			if (_wasLocalPlayerInRange)
			{
				if (IsLocalPlayerInRange(_talkBalloonData->talkRange * METER_TO_CM + _additionalDist))
				{ // ąüŔ§ ľČ -> ąüŔ§ ľČ : °»˝Ĺ
					UpdateTalkBalloon(InDeltaTime);
				}
				else
				{ // ąüŔ§ ľČ -> ąüŔ§ ąŰ : Ăâ·Â ÁßÁö
					EndTalkBalloon();
				}
			}
			else
			{
				if (IsLocalPlayerInRange(_talkBalloonData->talkRange * METER_TO_CM))
				{ // ąüŔ§ ąŰ -> ąüŔ§ ľČ : Ăâ·Â ˝ĂŔŰ
					StartTalkBalloon();
				}
			}
		}
		else
		{
			if (!_isOptionEnd)
			{
				_isOptionEnd = true;
				EndTalkBalloon();
			}
		}

		// ĹŘ˝şĆ®°ˇ şŻÇĎ´Â ¸đ˝ŔŔĚ ş¸ŔĚÁö ľĘ´Â Ć®¸Ż
		if (_tick2)
		{
			_panelTalkBalloon->SetRenderOpacity(1);
			_tick1 = false;
			_tick2 = false;
		}

		if (_tick1)
		{
			_tick1 = false;
			_tick2 = true;
		}
	}

	// ¸»ÇłĽ± Ăâ·Â °Ĺ¸®(µđąö±×żë)
	if (_isDebuging)
	{
		if (nullptr != _talkBalloonData)
		{
			DrawDebugTalkBalloonRange();
		}
	}
}

void UGsUIBillboardTalkBalloon::OnChangeRenderState(bool bIsRendered)
{
	SetRenderOpacity(bIsRendered ? 1.f : 0.f);
}

void UGsUIBillboardTalkBalloon::UpdateTalkBalloon(float InDeltaTime)
{
	// °˘ »óĹÂżˇ ´ëÇŃ ľ÷µĄŔĚĆ® ÇÔĽö ˝ÇÇŕ
	if (_updateDelegateMap.Contains(_talkBalloonState))
	{
		_updateDelegateMap[_talkBalloonState].ExecuteIfBound(InDeltaTime);
	}
}

void UGsUIBillboardTalkBalloon::UpdateOpened(float InDeltaTime)
{
	_remainKeepTime -= InDeltaTime;

	if (0 >= _remainKeepTime)
	{
		if (1 < _remainIntervalTime)
		{ // ´ë±â ˝Ă°ŁŔĚ 1ĂĘ°ˇ łŃŔ¸¸é Ĺő¸íµµ°ˇ żĂ¶ó°ˇ´Â Čż°ú°ˇ ŔÖ´Â Ľű±č Ăł¸®
			SetCloseWithEffect();
		}
		else
		{ // ´ë±â ˝Ă°ŁŔĚ ÂŞŔ¸¸é ąŮ·Î Ľű±č Ăł¸®
			SetClose();
		}
	}
}

void UGsUIBillboardTalkBalloon::UpdateClosing(float InDeltaTime)
{
	_remainIntervalTime -= InDeltaTime;

	float spendingTime = _talkBalloonData->talkBalloonDataSetList[_currentIndex].intervalTime - _remainIntervalTime;
	if (_remainIntervalTime < 0 || 1 < spendingTime)
	{
		SetClose();
	}
}

void UGsUIBillboardTalkBalloon::UpdateClosed(float InDeltaTime)
{
	_remainIntervalTime -= InDeltaTime;

	if (0 >= _remainIntervalTime)
	{
		_nextState = _currentState;
		UpdateData(TalkBalloonUpdateType::NORMAL);
	}
}

void UGsUIBillboardTalkBalloon::StartTalkBalloon()
{
	_wasLocalPlayerInRange = true;

	if (_gameObjectDelegate.Num() == 0)
	{
		if (UGsGameObjectManager* gameObjectManager = GSGameObject())
		{
			if (UGsGameObjectNonPlayerBase* nonPlayer =
				Cast<UGsGameObjectNonPlayerBase>(gameObjectManager->FindObject(_attachedActor, EGsGameObjectType::NonPlayerBase)))
			{
				const FGsSchemaNpcData* npcData = nonPlayer->GetNpcData();
				// ÄżąÂ´ĎĆĽ ĽŇłŕżë ¸»ÇłĽ± Ăł¸® (Ľ­ąö Ĺë˝Ĺ)
				if (npcData && npcData->npcFunctionType == NpcFunctionType::COMMUNITY)
				{
					_gameObjectDelegate.Emplace(GMessage()->GetGameObject().AddUObject(MessageGameObject::TALKBALLOON_COMMUNITY_RANK,
						this, &UGsUIBillboardTalkBalloon::OnReceiveCommunityRank));
					_gameObjectDelegate.Emplace(GMessage()->GetGameObject().AddUObject(MessageGameObject::TALKBALLOON_COMMUNITY_MARKET,
						this, &UGsUIBillboardTalkBalloon::OnReceiveCommunityMarket));
				}
			}
		}
	}

	_talkBalloonState = TalkBalloonState::Closed;
	_remainIntervalTime = 0;
}

void UGsUIBillboardTalkBalloon::EndTalkBalloon()
{
	_isRequestingData = false;
	_wasLocalPlayerInRange = false;
	_remainIntervalTime = 0;

	if (FGsMessageHolder* msg = GMessage())
	{
		if (_gameObjectDelegate.Num() > 0)
		{
			for (auto iter : _gameObjectDelegate)
			{
				msg->GetGameObject().Remove(iter);
			}
			_gameObjectDelegate.Empty();
		}
	}

	SetClose();
}

void UGsUIBillboardTalkBalloon::SetOpen()
{
	_talkBalloonState = TalkBalloonState::Opened;

	if (_updateReason == TalkBalloonUpdateType::NORMAL && _talkBalloonData->talkRandomRate < FMath::RandRange(0, 10000))
	{
		return;
	}

	OnStateChanged.Broadcast();

	// 2Ć˝ ČÄżˇ ¸»ÇłĽ±ŔĚ ş¸ŔÎ´Ů.
	_panelTalkBalloon->SetVisibility(ESlateVisibility::HitTestInvisible);
	_panelTalkBalloon->SetRenderOpacity(0);
	_tick1 = true;
}

void UGsUIBillboardTalkBalloon::SetCloseWithEffect()
{
	_talkBalloonState = TalkBalloonState::Closing;
	PlayCloseAnimation();
}

void UGsUIBillboardTalkBalloon::SetClose()
{
	_talkBalloonState = TalkBalloonState::Closed;
	OnStateChanged.Broadcast();

	_panelTalkBalloon->SetVisibility(ESlateVisibility::Collapsed);
}

void UGsUIBillboardTalkBalloon::UpdateData(TalkBalloonUpdateType InUpdateReason)
{
	// Á×Ŕş »óĹÂŔĎ ¶§´Â ¸»ÇłĽ±Ŕ» °»˝ĹÇĎÁö ľĘ´Â´Ů.
	if (_isDead)
		return;

	// ¸»ÇłĽ± ±âş» µĄŔĚĹÍ ( Ăâ·Â ąüŔ§, ·Ł´ýĽş ) Č®ŔÎ
	if (nullptr == _talkBalloonData)
		return;
	
	_updateReason = InUpdateReason;
	switch (InUpdateReason)
	{
	case TalkBalloonUpdateType::NORMAL:
		UpdateDataNormal(_currentOrder);
		break;
	case TalkBalloonUpdateType::STATE_CHANGED:
		UpdateDataNormal(_currentOrder);
		break;
	case TalkBalloonUpdateType::ANIM_NOTIFIED:
		UpdateDataAnimNotified();
		break;
	case TalkBalloonUpdateType::COMMUNITY:
		UpdateDataOnReceiveCommunity();
		break;
	case TalkBalloonUpdateType::HIT:
		UpdateDataOnHit();
	}
}

void UGsUIBillboardTalkBalloon::UpdateDataNormal(int32 InCurrentOrder, int32 InCount)
{
	// Ľ­ąö µĄŔĚĹÍ¸¦ żäĂ» ÁßŔÎ°ˇ?
	if (_isRequestingData)
		return;
	
	// Ăâ·ÂÇŇ ´ë»ç ¸ń·ĎŔĚ Á¸ŔçÇĎ´Â°ˇ?
	if (!_displayIndexListMap.Contains(_nextState))
		return;

	// ´ë»ç ¸ń·ĎŔ» ´Ů Č®ŔÎÇß´Â°ˇ?
	if (InCount >= _displayIndexListMap[_nextState].Num())
		return;

	// ľÖ´Ď¸ŢŔĚĽÇ »óĹÂ°ˇ şŻÇß´Â°ˇ?
	if (_currentState != _nextState)
	{
		_currentState = _nextState;
		_currentOrder = INDEX_NONE;
		_isDead = (EGsTalkBalloonState::Dead == _nextState);
		_randomIndexList.Empty();
	}

	int32 nextOrder = GetNextOrder(InCurrentOrder);
	int32 nextIndex = GetOriginalIndex(nextOrder);

	_currentOrder = nextOrder;
	_currentIndex = nextIndex;

	// µĄŔĚĹÍ żäĂ»ŔĚ ÇĘżäÇŃ°ˇ? (ÄżąÂ´ĎĆĽĽŇłŕ)
	if (IsRequiredDataRequest(_currentIndex))
	{
		RequestServerData(_currentIndex);
		return;
	}

	// °ü·Ă µĄŔĚĹÍ°ˇ ŔŻČżÇŃ°ˇ?
	if (CanShowTalkBalloon(_currentIndex))
	{
		SetNextDataByIndex(_currentIndex);
		SetOpen();
	}
	else
	{
		// ÇöŔç ¸»ÇłĽ±Ŕ» ÇĄ˝ĂÇŇ Ľö ľřŔ¸¸é ´Ů˝Ă ŔÎµ¦˝ş Č®ŔÎ
		UpdateDataNormal(InCurrentOrder + 1, InCount + 1);
	}
}

void UGsUIBillboardTalkBalloon::UpdateDataStateChanged()
{

}

void UGsUIBillboardTalkBalloon::UpdateDataAnimNotified()
{
	_remainKeepTime = _animNotifiedDataSet->keepTime;
	_remainIntervalTime = _animNotifiedDataSet->intervalTime;
	SetText(_animNotifiedDataSet->text);

	SetOpen();

	_animNotifiedDataSet = nullptr;
}

void UGsUIBillboardTalkBalloon::UpdateDataOnReceiveCommunity()
{
	_isRequestingData = false;

	if (!_wasLocalPlayerInRange)
		return;

	if (CanShowTalkBalloon(_currentIndex))
	{
		SetNextDataByIndex(_currentIndex);
		SetOpen();
	}
	else
	{
		_nextState = _currentState;
		UpdateData(TalkBalloonUpdateType::NORMAL);
	}
}

void UGsUIBillboardTalkBalloon::UpdateDataOnHit()
{
	if (_displayIndexListMap.Contains(EGsTalkBalloonState::Hit))
	{
		int32 index = _displayIndexListMap[EGsTalkBalloonState::Hit][0];
		SetNextDataByIndex(index);
		SetOpen();
	}
}

void UGsUIBillboardTalkBalloon::SetTalkBalloonData(const FGsSchemaTalkBalloonData* InSchemaData)
{
	_talkBalloonData = InSchemaData;

	InitDisplayIndexList();
}

void UGsUIBillboardTalkBalloon::SetActor(AActor* InActor)
{
	_attachedActor = InActor;
}

void UGsUIBillboardTalkBalloon::SetText(const FText& InText)
{
	auto MinDesiredWidth = _textBlockTalk->GetDesiredSize();

	FString str = InText.ToString();
	float textWidth = ComputeDesiredSize(FText::FromString(str)) + 40.f;

	if (textWidth > 270.f)
	{
		str = str.Left(10);
		textWidth = ComputeDesiredSize(FText::FromString(str)) + 40.f;
	}

	_textBlockTalk->SetMinDesiredWidth(textWidth);
	_textBlockTalk->SetText(InText);
}

void UGsUIBillboardTalkBalloon::SetActorState(uint8 InState)
{
	EGsTalkBalloonState state = GetStateEnumFromString(InState);
	if (state == EGsTalkBalloonState::MAX)
		return;

	if (_currentState == state)
		return;

	if (_displayIndexListMap.Contains(state))
	{
		_nextState = state;
		UpdateData(TalkBalloonUpdateType::STATE_CHANGED);
	}
}

void UGsUIBillboardTalkBalloon::ShowNotifiedTalkBallon(const FGsSchemaTalkBalloonDataSet* InSchemaDataSet)
{
	_animNotifiedDataSet = InSchemaDataSet;
	if (_animNotifiedDataSet)
	{
		UpdateData(TalkBalloonUpdateType::ANIM_NOTIFIED);
	}
}

void UGsUIBillboardTalkBalloon::SetIsDead(bool InIsDead)
{
	_isDead = InIsDead;
}

bool UGsUIBillboardTalkBalloon::IsLocalPlayerInRange(int32 InRadius)
{
	if (nullptr == _localPlayer)
	{
		if (UGsGameObjectManager* gameObjectManager = GSGameObject())
		{
			_localPlayer = gameObjectManager->FindObject(EGsGameObjectType::LocalPlayer);
		}
	}

	if (nullptr != _localPlayer && nullptr != _attachedActor)
	{
		float distSquared = FVector2D::DistSquared(_localPlayer->GetLocation2D(), FVector2D(_attachedActor->GetActorLocation()));
		if (distSquared <= InRadius * InRadius)
		{
			return true;
		}
	}
	return false;
}

bool UGsUIBillboardTalkBalloon::IsRequiredDataRequest(int32 InIndex)
{
	if (_talkBalloonData)
	{
		switch (_talkBalloonData->talkBalloonDataSetList[InIndex].dataSetType)
		{
		case EGsTalkBalloonDataType::RANK_LOCAL_LEVEL_1ST:
		case EGsTalkBalloonDataType::RANK_WORLD_LEVEL_1ST:
		case EGsTalkBalloonDataType::MARKET_PRICE_TOP:
		case EGsTalkBalloonDataType::MARKET_WEAPON_GRADE_TOP:
			return true;
		}
	}
	return false;
}

bool UGsUIBillboardTalkBalloon::CanShowTalkBalloon(int32 InIndex)
{
	if (_talkBalloonData)
	{
		switch (_talkBalloonData->talkBalloonDataSetList[InIndex].dataSetType)
		{
		case EGsTalkBalloonDataType::RANK_LOCAL_LEVEL_1ST:
			if (_localUserName.IsEmpty())
				return false;
			break;
		case EGsTalkBalloonDataType::RANK_WORLD_LEVEL_1ST:
			if (_worldUserName.IsEmpty())
				return false;
			break;
		case EGsTalkBalloonDataType::MARKET_PRICE_TOP:
			if (_highestPriceItemId == INVALID_ITEM_ID)
				return false;
			break;
		case EGsTalkBalloonDataType::MARKET_WEAPON_GRADE_TOP:
			if (_highestGradeItemId == INVALID_ITEM_ID)
				return false;
			break;
		case EGsTalkBalloonDataType::REDDOT_REWARD:
		case EGsTalkBalloonDataType::REDDOT_NEWS:
		case EGsTalkBalloonDataType::ANNOUNCEMENT:
			if (FGsCommunityEventManager* communityManager = GSCommunityEvent())
			{
				if (!communityManager->IsRedDot())
					return false;
			}
			break;
		}

		return true;
	}
	return false;
}

bool UGsUIBillboardTalkBalloon::IsClosed()
{
	return (_talkBalloonState == TalkBalloonState::Closed) ? true : false;
}

bool UGsUIBillboardTalkBalloon::IsOptionEnabled()
{
	if (UGsGameUserSettings* gameUserSettings = GGameUserSettings())
	{
		int32 optionValue = gameUserSettings->GetCombatSetting(EGsOptionCombat::NPC_TALK_BALLOON);
		return (0 == optionValue) ? false : true;
	}
	
	return false;
}

int32 UGsUIBillboardTalkBalloon::GetNextOrder(int32 InOrder)
{
	int32 dataSize = _displayIndexListMap[_currentState].Num();
	if (0 == dataSize)
		return 0;

	int32 nextOrder = InOrder + 1;
	if (nextOrder >= dataSize)
	{
		nextOrder %= dataSize;
	}
	return nextOrder;
}

int32 UGsUIBillboardTalkBalloon::GetOriginalIndex(int32 InIndex)
{
	switch (_talkBalloonData->talkType)
	{
	case EGsTalkType::ORDER:
		return _displayIndexListMap[_currentState][InIndex];
	case EGsTalkType::RANDOM:
	{
		if (InIndex == 0 || _randomIndexList.Num() == 0)
		{
			ResetRandomIndexList();
		}
		return _randomIndexList[InIndex];
	}
	}
	return 0;
}

FText UGsUIBillboardTalkBalloon::GetNextText(int32 InIndex)
{
	switch (_talkBalloonData->talkBalloonDataSetList[InIndex].dataSetType)
	{
	case EGsTalkBalloonDataType::RANK_LOCAL_LEVEL_1ST:
	{
		FText findText;
		if (_localGuildName.IsEmpty())
		{
			FText::FindText(TEXT("TalkBalloonText"), TEXT("TalkBallon_ServerRank_Local_02"), findText);
			return FText::Format(findText, FText::FromString(_localUserName));
		}
		else
		{
			FText::FindText(TEXT("TalkBalloonText"), TEXT("TalkBallon_ServerRank_Local_01"), findText);
			return FText::Format(findText, FText::FromString(_localGuildName), FText::FromString(_localUserName));
		}
		break;
	}
	case EGsTalkBalloonDataType::RANK_WORLD_LEVEL_1ST:
	{
		FText findText;
		if (_worldGuildName.IsEmpty())
		{
			FText::FindText(TEXT("TalkBalloonText"), TEXT("TalkBallon_ServerRank_World_02"), findText);
			return FText::Format(findText, FText::FromString(_worldUserName));
		}
		else
		{
			FText::FindText(TEXT("TalkBalloonText"), TEXT("TalkBallon_ServerRank_World_01"), findText);
			return FText::Format(findText, FText::FromString(_worldGuildName), FText::FromString(_worldUserName));
		}
		break;
	}
	case EGsTalkBalloonDataType::MARKET_PRICE_TOP:
	{
		const FGsSchemaItemCommon* itemData = UGsItemManager::GetItemTableDataByTID(_highestPriceItemId);
		if (itemData)
		{
			return FText::Format(_talkBalloonData->talkBalloonDataSetList[InIndex].text, itemData->name);
		}
		break;
	}
	case EGsTalkBalloonDataType::MARKET_WEAPON_GRADE_TOP:
	{
		const FGsSchemaItemCommon* itemData = UGsItemManager::GetItemTableDataByTID(_highestGradeItemId);
		if (itemData)
		{
			return FText::Format(_talkBalloonData->talkBalloonDataSetList[InIndex].text, itemData->name);
		}
		break;
	}
	case EGsTalkBalloonDataType::ACHIEVEMENT_LOGIN_ACCUMULATE:
	{	 
		if(auto achievementData = GSAchivement()->FindAchievementDataByConditionType(AchievementType::LOGIN_ACCUMULATE).Pin())
		{
			uint64 accessDate = achievementData->CurrentPoint();
			return FText::Format(_talkBalloonData->talkBalloonDataSetList[InIndex].text, FText::AsNumber(accessDate));
		}
		break;
	}
	case EGsTalkBalloonDataType::ACHIEVEMENT_CREATE_DATE:
	{
		const FGsNetUserData* userData = GGameData()->GetUserData();

		FTimespan createdTime = FGsTimeSyncUtil::ConvertToDateTime(userData->_createdTime) - FDateTime(0);
		FTimespan currentTime = FGsTimeSyncUtil::GetServerNowDateTime() - FDateTime(0);

		int32 diffDay = currentTime.GetDays() - createdTime.GetDays() + 1;

		return FText::Format(_talkBalloonData->talkBalloonDataSetList[InIndex].text, FText::FromString(userData->mUserName), FText::AsNumber(diffDay));
	}
	}
	return _talkBalloonData->talkBalloonDataSetList[InIndex].text;
}

EGsTalkBalloonState UGsUIBillboardTalkBalloon::GetStateEnumFromString(uint8 InState)
{
	FString InStrState = GetEnumToString(EGsStateBase, EGsStateBase(InState));
	int32 NewDoubleColonIndex = InStrState.Find(TEXT("::"), ESearchCase::CaseSensitive);
	if (NewDoubleColonIndex != INDEX_NONE)
	{
		InStrState = InStrState.RightChop(NewDoubleColonIndex + 2);
	}

	for (uint8 i = 0; i < (uint8)EGsTalkBalloonState::MAX; ++i)
	{
		FString strState = GetEnumToString(EGsTalkBalloonState, EGsTalkBalloonState(i));
		NewDoubleColonIndex = strState.Find(TEXT("::"), ESearchCase::CaseSensitive);
		if (NewDoubleColonIndex != INDEX_NONE)
		{
			strState = strState.RightChop(NewDoubleColonIndex + 2);
		}

		if (strState.Compare(InStrState) == 0)
		{
			return EGsTalkBalloonState(i);
		}
	}
	
	return EGsTalkBalloonState::MAX;
}

void UGsUIBillboardTalkBalloon::RequestServerData(int32 InIndex)
{
	if (_talkBalloonData)
	{
		switch (_talkBalloonData->talkBalloonDataSetList[_currentIndex].dataSetType)
		{
		case EGsTalkBalloonDataType::RANK_LOCAL_LEVEL_1ST:
		case EGsTalkBalloonDataType::RANK_WORLD_LEVEL_1ST:
			_isRequestingData = true;
			FGsNetSendService::SendReqCommunityTalkRank();
			return;
		case EGsTalkBalloonDataType::MARKET_PRICE_TOP:
		case EGsTalkBalloonDataType::MARKET_WEAPON_GRADE_TOP:
			_isRequestingData = true;
			FGsNetSendService::SendReqCommunityTalkMarket();
			return;
		}
	}
}

void UGsUIBillboardTalkBalloon::SetNextDataByIndex(int32 InIndex)
{
	_remainKeepTime = _talkBalloonData->talkBalloonDataSetList[InIndex].keepTime;
	_remainIntervalTime = _talkBalloonData->talkBalloonDataSetList[InIndex].intervalTime;
	SetText(GetNextText(InIndex));
}

void UGsUIBillboardTalkBalloon::ResetRandomIndexList()
{
	int32 dataSize = _displayIndexListMap[_currentState].Num();
	if (0 == dataSize)
		return;

	_randomIndexList.Empty();
	for (int32 i = 0; i < dataSize; ++i)
	{
		_randomIndexList.Emplace(_displayIndexListMap[_currentState][i]);
	}

	// Shuffle
	FRandomStream rand;
	rand.GenerateNewSeed();
	for (int32 i = 0; i < dataSize; ++i)
	{
		int32 randomPosition = rand.RandHelper(dataSize);
		int32 temp = _randomIndexList[i];
		_randomIndexList[i] = _randomIndexList[randomPosition];
		_randomIndexList[randomPosition] = temp;
	}
}

void UGsUIBillboardTalkBalloon::InitDisplayIndexList()
{
	if (_talkBalloonData)
	{
		_displayIndexListMap.Empty();
		EGsTalkBalloonState status = EGsTalkBalloonState::None;
		for (uint8 i = 0; i < _talkBalloonData->talkBalloonDataSetList.Num(); ++i)
		{
			status = _talkBalloonData->talkBalloonDataSetList[i].status;
			if (_displayIndexListMap.Contains(status))
			{
				_displayIndexListMap[status].Emplace(i);
			}
			else
			{
				_displayIndexListMap.Emplace(status, TArray<int32>());
				_displayIndexListMap[status].Emplace(i);
			}
		}
	}
}

float UGsUIBillboardTalkBalloon::ComputeDesiredSize(const FText& InText) const
{
	const FVector2D LocalShadowOffset = _textBlockTalk->ShadowOffset;
	const float LocalOutlineSize = _textBlockTalk->Font.OutlineSettings.OutlineSize;

	const FVector2D ComputedOutlineSize(LocalOutlineSize * 2, LocalOutlineSize);
	if (FSlateRenderer* renderer = FSlateApplication::Get().GetRenderer())
	{		
		const FVector2D TextSize = renderer->GetFontMeasureService()->Measure(InText, _textBlockTalk->Font) + ComputedOutlineSize + LocalShadowOffset;
		return TextSize.X;
	}

	auto MinDesiredWidth = _textBlockTalk->GetDesiredSize();
	return MinDesiredWidth.X;
}

void UGsUIBillboardTalkBalloon::DrawDebugTalkBalloonRange()
{
	if (nullptr == _attachedActor)
		return;

	UWorld* world = GetWorld();
	if (world)
	{
		// ¸»ÇłĽ± Ăâ·Â °Ĺ¸®
		DrawDebugCircle(world, _attachedActor->GetActorLocation(),
			_talkBalloonData->talkRange * METER_TO_CM, 100, FColor::Blue, false, 1.f,
			0, 0.0f, FVector(1.f, 0.f, 0.f), FVector(0.f, 1.f, 0.f));

		// PC°ˇ NPCżÍ ¸ÖľîÁú ¶§ ¸»ÇłĽ±ŔĚ ş¸ŔĚ´Â °Ĺ¸®
		DrawDebugCircle(world, _attachedActor->GetActorLocation(),
			_talkBalloonData->talkRange * METER_TO_CM + _additionalDist, 100, FColor::Green, false, 1.f,
			0, 0.0f, FVector(1.f, 0.f, 0.f), FVector(0.f, 1.f, 0.f));
	}
}

void UGsUIBillboardTalkBalloon::SetDrawDebugTalkBalloonRange(bool InVisible)
{
	_isDebuging = InVisible;
}

void UGsUIBillboardTalkBalloon::OnReceiveCommunityRank(const IGsMessageParam* InParam)
{
	const FGsTalkBalloonRankMessageParam* param = InParam->Cast<const FGsTalkBalloonRankMessageParam>();
	if (param)
	{
		_localGuildName = param->_localGuildName;
		_localUserName = param->_localUserName;
		_worldGuildName = param->_worldGuildName;
		_worldUserName = param->_worldUserName;
	}

	UpdateData(TalkBalloonUpdateType::COMMUNITY);
}

void UGsUIBillboardTalkBalloon::OnReceiveCommunityMarket(const IGsMessageParam* InParam)
{
	const FGsTalkBalloonMarketMessageParam* param = InParam->Cast<const FGsTalkBalloonMarketMessageParam>();
	if (param)
	{
		_highestPriceItemId = param->_highestPriceItemId;
		_highestGradeItemId = param->_highestGradeItemId;
	}

	UpdateData(TalkBalloonUpdateType::COMMUNITY);
}

void UGsUIBillboardTalkBalloon::OnHit()
{
	UpdateData(TalkBalloonUpdateType::HIT);
}
