
#include "GsUIDungeonSlotEntry.h"
#include "Dungeon/GsDungeonData.h"
#include "Dungeon/GsDungeonHelper.h"
#include "UTIL/GsUIUtil.h"
#include "UI/UIControlLib/ContentWidget/GsButton.h"
#include "Image.h"
#include "TextBlock.h"
#include "UserWidget.h"

#include "Dungeon/GsSchemaDungeonData.h"
#include "Shared/Shared/SharedInclude/SharedTypes.h"
#include "Shared/Client/SharedEnums/SharedCommonEnum.h"
#include "T1Project.h"


void UGsUIDungeonSlotEntry::NativeOnInitialized()
{
	_btnClicked->OnClicked.AddDynamic(this, &UGsUIDungeonSlotEntry::OnClickSelected);

	Super::NativeOnInitialized();
}

void UGsUIDungeonSlotEntry::OnClickSelected()
{
	if (_toggleCallback)
	{
		_toggleCallback(_indexInGroup, true);
	}
}

void UGsUIDungeonSlotEntry::SetData(const FGsDungeonData* InDungeonData)
{
	if (nullptr == InDungeonData)
	{
		return;
	}

	_dungeonData = InDungeonData;

	/**
	 * Set Dungeon Name
	 */
	FText format;
	// 2023/2/28 PKT - ЗцАз ёрөО ГюАё·О ЗҘұв
	FGsDungeonHelper::FindText(TEXT("UI_Dungeon_Floor"), format);
	_textName->SetText(FText::Format(format, { _dungeonData->GetSchema()->indexValue }));

	Invalidate();
}

void UGsUIDungeonSlotEntry::Invalidate()
{
	if (nullptr == _dungeonData)
	{
		GSLOG(Error, TEXT("nullptr == _dungeonData"));
		return;
	}

	// 2022/08/17 PKT - ұЧ·м БӨәёҝН ҙшАь БӨәё ёрөО ҫр¶фАМ З®·БҫЯ өхөеёҰ ЗШБҰ ЗСҙЩ.
	bool isUnLockContents = _dungeonData->IsUnLockState();
	_imgDimmed->SetVisibility(isUnLockContents ? ESlateVisibility::Collapsed : ESlateVisibility::SelfHitTestInvisible);
}

void UGsUIDungeonSlotEntry::SetIsSelected(bool bInIsSelected)
{
	if (_imgSelectedEdge)
	{
		_imgSelectedEdge->SetVisibility(bInIsSelected ? ESlateVisibility::SelfHitTestInvisible : ESlateVisibility::Collapsed);
	}
}

bool UGsUIDungeonSlotEntry::GetIsSelected() const
{
	if (_imgSelectedEdge)
	{
		return ESlateVisibility::SelfHitTestInvisible == _imgSelectedEdge->GetVisibility();
	}

	return false; 
}

const FGsDungeonData* UGsUIDungeonSlotEntry::GetData() const
{
	return _dungeonData;
}